# Generated by Django 5.2.6 on 2025-09-26 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payer_name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('Cedula', 'Cédula'), ('Pasaporte', 'Pasaporte')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('card_number_masked', models.CharField(blank=True, max_length=30)),
                ('card_expiry', models.CharField(blank=True, max_length=7)),
                ('card_cvv_masked', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
